[package]
name = "jxl-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.jxl]
path = ".."
features = ["encoder"]

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "decode"
path = "fuzz_targets/decode.rs"
test = false
doc = false

[[bin]]
name = "decode_header"
path = "fuzz_targets/decode_header.rs"
test = false
doc = false

[[bin]]
name = "encode_bit_writer_roundtrip"
path = "fuzz_targets/encode_bit_writer_roundtrip.rs"
test = false
doc = false

[[bin]]
name = "encode_vardct_smoke"
path = "fuzz_targets/encode_vardct_smoke.rs"
test = false
doc = false

[[bin]]
name = "encode_api_smoke"
path = "fuzz_targets/encode_api_smoke.rs"
test = false
doc = false

[[bin]]
name = "encode_progressive_alpha_smoke"
path = "fuzz_targets/encode_progressive_alpha_smoke.rs"
test = false
doc = false
